name: Copy To Ec2
description: 'Copy files To Ec2'
secrets:
  ec2IP:
    required: true
  awsAccessKeyId:
    required: true
  awsSecretKey:
    required: true
  awsRegion: 
    required: true
  ec2User:
    required: true
  secuityGroupId:
    required: true
  sshKey:
    required: true
  fileToCopy:
    required: true
  destination:
    required: true
  unzipDestination: 
    required: true

jobs:
  copy-to-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        run: echo "ELASTIC_IP=${{ secrets.ec2User }}@${{ secrets.ec2IP }}" >> $GITHUB_ENV

      - name: Get Runner IP
        run: |
          IP_ADDRESS=$(curl -s https://api.ipify.org)
          echo "IP_ADDRESS=$IP_ADDRESS" >> $GITHUB_ENV

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.awsAccessKeyId }}
          aws-secret-access-key: ${{ secrets.awsSecretKey }}
          aws-region: ${{ secrets.awsRegion }}
      
      - name: Update Security Group
        run: |
          SECURITY_GROUP_ID="${{ secrets.secuityGroupId }}"
          IP_ADDRESS=${{ env.IP_ADDRESS }}
          aws ec2 authorize-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${IP_ADDRESS}/32

      - name: Setup SSH Key
        env:
          SSH_PRIVATE_KEY_FOR_EC2: ${{ secrets.sshKey }}
        run: |
            echo "$SSH_PRIVATE_KEY_FOR_EC2" > SSH_PRIVATE_KEY_FOR_EC2.pem
            chmod 600 SSH_PRIVATE_KEY_FOR_EC2.pem

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.ec2IP }} >> ~/.ssh/known_hosts
          
      - name: Copy ZIP FILE to EC2
        run: | 
          rsync -avz -e 'ssh -i SSH_PRIVATE_KEY_FOR_EC2.pem' ${{ secrets.fileToCopy }}  ${{ env.ELASTIC_IP }}:{{ secrets.destination }}

      - name: Unzip  flutterFlow Web Build on EC2
        run: |
          ssh -i SSH_PRIVATE_KEY_FOR_EC2.pem ${{ env.ELASTIC_IP }} << 'EOF'
          unzip -o {{ secrets.destination }} -d {{ secrets.unzipDestination }}
          cd {{ secrets.unzipDestination }}
          rm -rf {{ secrets.destination }}
          EOF

      - name: Remove Added Security Group Rule
        run: |
          SECURITY_GROUP_ID="${{ secrets.secuityGroupId }}"
          aws ec2 revoke-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 22 \
            --cidr ${IP_ADDRESS}/32
